### ISSUE TITLE
How to fix a part of joints of the model in simulation?

### ISSUE THREAD

**Issue by Uptomylimit** [google-deepmind/dm_control#424]
Hi,

I'm a student and I'm trying to use MuJoCo for simulation.

I'm trying to fix a part of joints of my model in simulation, so that a part of my model won't move. Is there any way to do this?

**Comment by yuvaltassa** [comment]
Delete (comment out) the joint.

Note [this gotcha](https://mujoco.readthedocs.io/en/2.3.7/overview.html#surprising-collisions)
