### ISSUE TITLE
Will dm_control support GPU & TPU acceleration based on MuJoCo 3

### ISSUE THREAD

**Issue by RayYoh** [google-deepmind/dm_control#429]
Hello, developers. Thanks for your excellent work. I just see that MuJoCo 3 has been released, it is surprisingly GPU acceleration. As we all know. dm_control has been a good benchmark, so I would like to ask that whether any plan to update dm_control based on the features of MuJoCo3. I think it will be a good progress for RL  research.

**Comment by saran-t** [comment]
The answer at the moment is no, we don't plan to retrofit MJX into dm_control.

Having said that, we'd be supportive of a community-driven effort to do so. I think anything that touches `composer` is likely to end up with scenes that are far too complex to be run efficiently in MJX, however the `suite` should work well and not be too hard to do.

A word of warning though, the simulation you get from MJX won't be identical to MuJoCo, so for the purpose of RL benchmarking the performance may not be directly comparable.

**Comment by RayYoh** [comment]
Got that. Thanks for your reply, and thanks for your excellent work.
