### ISSUE TITLE
"rope" composite type is deprecated

### ISSUE THREAD

**Issue by matansudry** [google-deepmind/dm_control#433]
Hi,

Something was changed in my requirements list, and now I am getting this error that was a warning before, any idea what was upgraded or what needs to be changed to allow "rope" composite?

"ValueError: XML Error: The "rope" composite type is deprecated. Please use "cable" instead"

**Comment by quagla** [comment]
Hi @matansudry, it's not supported anymore in MuJoCo 3. It has been replaced by either the composite cable (for unstretchable cables) or the flex 1d (for stretchable cables with no bending/twist).
