### ISSUE TITLE
Can we directly change the mass / damping of the robot?

### ISSUE THREAD

**Issue by yingchengyang** [google-deepmind/dm_control#441]
After making an environment-task like Cheetah-run (i.e., env=suite.load('cheetah', 'run')), can we directly change the mass / damping of the robot by directly changing the number of env._physics.model.body_mass / env._physics.model.dof_damping? 

Thanks a lot!

**Comment by yuvaltassa** [comment]
Damping you can just change, yes.

It is not recommended to change mass as other fields depend on it. The safe thing to do is change it in the XML and reload. You can do this easily by introducing a Python string replace or format in the env loader. Unless you want to do this in the middle of the episode. If that's what you want to do I can tell what you need to change in the mjModel.

**Comment by yingchengyang** [comment]
Thanks a lot for your answer. As for the mass, if I change the env._physics.model.body_mass only in the stage of setting up the environment, like 

env = suite.load("cheetah", "run")
env._physics.model.body_mass = 1.1 * env._physics.model.body_mass

Then I will no longer change the mass and utilize this env. Is it legal or effective? Thanks a lot again!

**Comment by yingchengyang** [comment]
Moreover, I check the xml files of Walker and Cheetah. In my opinion, <compiler settotalmass="14"/> in cheetah.xml means that the mass of Cheetah is 14. However, I do not find some codes to directly represent the mass of Walker in walker.xml. How can I change the mass of Walker? Thanks a lot!

**Comment by yuvaltassa** [comment]
[These two functions](https://mujoco.readthedocs.io/en/latest/APIreference/APIfunctions.html#mj-gettotalmass) might be helpful.

**Comment by yuvaltassa** [comment]
When you scale mass you should also scale the corresponding body_inertia

**Comment by yingchengyang** [comment]
Thanks a lot!
