### ISSUE TITLE
Update to MuJoCo V3.1.0

### ISSUE THREAD

**Issue by peterdavidfagan** [google-deepmind/dm_control#443]
Happy to start a pr for this, latest changes are useful for my project.

**Comment by nimrod-gileadi** [comment]
We'll be pushing 3.1.1 soon with some bugfixes, and will update dm_control then. Sorry for the wait.

**Comment by nimrod-gileadi** [comment]
We just pushed version 1.0.16 of dm_control which targets mujoco 3.1.1.

Let us know if there are any problems.
