### ISSUE TITLE
[PyMJCF] SDF plugin integration

### ISSUE THREAD

**Issue by driesmarzougui** [google-deepmind/dm_control#444]
Hi! I am integrating the ["mujoco.sdf.sdflib"](https://github.com/google-deepmind/mujoco/blob/main/model/plugin/sdf/cow.xml) plugin into my model (SDF generation for meshes). My model is dynamically defined using PyMJCF. It however seems like the SDF plugin is currently unsupported by PyMJCF.

Required changes:
* Allow `sdf` to be the type of a geom
* Allow the `geom/plugin` element
* Allow the `asset/mesh/plugin` element

**Comment by nimrod-gileadi** [comment]
This should be possible now, with version 1.0.16 of dm_control.
