### ISSUE TITLE
Cannot reproduce the joining of parent and child models in "Attaching models" section of mjcf.

### ISSUE THREAD

**Issue by barikata1984** [google-deepmind/dm_control#451]
Hi all, 

I am trying to join two models in my code: 6 dof arm and end-effector. I thought that [Attaching models](https://github.com/google-deepmind/dm_control/tree/b002aa350c3a48e44ecef84bd5dab6d08e1b2f74/dm_control/mjcf#attaching-models) of `mjcf` is the section describing how to achieve it, so I tried to reproduce the attachment of `child` to `parent` as a starting point. I loaded `parent` and `child` from two XML files for each separately and got `family` with `.attach()` of `parent` as shown in the code below. The expected result of `family.to_xml_string()` was the string described as the final generated XML file in that section, but the actual output I got was different from it. How can I reproduce the final generated XML, or perform a similar model attachment with the MuJoCo tool suite?

Code: 
```Python
from dm_control import mjcf
from pathlib import Path


def main():
    models_dir = Path.cwd() / "models"
    parent_path = models_dir / "parent.xml"  # model file name
    child_path = models_dir / "child.xml"  # model file name

    parent = mjcf.from_path(parent_path)
    print(parent.to_xml_string())

    child = mjcf.from_path(child_path)
    print(child.to_xml_string())

    family = parent.attach(child)
    print(family.to_xml_string())  # I thought that this should print exactly the same as the final generated XML


if __name__ == "__main__":
    main()
```

Output: 
```
<mujoco model="parent">
  <default>
    <default class="/"/>
  </default>
  <worldbody>
    <body name="//unnamed_body_0">
      <geom name="foo" class="/" type="box" size="0.5 0.29999999999999999 0.10000000000000001" pos="-0.20000000000000001 0 0.29999999999999999"/>
      <site name="attachment_site" class="/" pos="1 2 3" quat="1 0 0 1"/>
    </body>
  </worldbody>
</mujoco>

<mujoco model="child">
  <default>
    <default class="/"/>
  </default>
  <worldbody>
    <geom name="bar" class="/" type="box" size="0.10000000000000001 0.20000000000000001 0.29999999999999999" pos="0.5 0.25 1"/>
  </worldbody>
</mujoco>

<body name="child/">
  <geom name="child/bar" class="child/" type="box" size="0.10000000000000001 0.20000000000000001 0.29999999999999999" pos="0.5 0.25 1"/>
</body>
```

**Comment by yuvaltassa** [comment]
Have a look [here](https://arxiv.org/abs/1801.00690) I think this is covered. Also search for `attach(` in the dm_control repo, there are many examples.
