### ISSUE TITLE
How to add a seed to custom environments?

### ISSUE THREAD

**Issue by jomian78** [google-deepmind/dm_control#456]
I've created my own custom environment for running learning experiments and believe that the images I am reading from a simulated camera may be a source of randomness. 

Is it possible to add a seed to a custom mujoco environment defined in xml?

For example:

`from dm_control import mujoco as mj`
`env = f'' # defined in xml`
`physics = mj.Physics.from_xml_string(env)`

can I create `physics` using a different function that takes a random seed call?

**Comment by yuvaltassa** [comment]
Unfortunately not. However the only place where you might get randomness in rendering is [random textures](https://mujoco.readthedocs.io/en/latest/XMLreference.html#asset-texture-random). So just remove that and everything will be deterministic.
