### ISSUE TITLE
1.0.21 release missing

### ISSUE THREAD

**Issue by GaetanLepage** [google-deepmind/dm_control#485]
Hello,

dm_control 1.0.20 is not compatible with the latest mujoco (3.2.0).
From https://github.com/google-deepmind/dm_control/commit/a495469c67265b082ff27e64010f844798ba1c2b, it seems that you are ready to release 1.0.21.
Is there any blocker for this or is it an omission ?

Thanks in advance :)

Context: bumping mujoco's version in nixpkgs: https://github.com/NixOS/nixpkgs/pull/327508

**Comment by kevinzakka** [comment]
I believe this is fixed now.
