### ISSUE TITLE
1.0.23

### ISSUE THREAD

**Issue by GaetanLepage** [google-deepmind/dm_control#497]
As of today, the latest version of `dm-control` listed on Pypi is 1.0.23.
However, no such release/tag exist on the GitHub repository.

Could you please tag this release ? This would help us, nixpkgs package maintainers, to properly update the package.

Thanks in advance :)

**Comment by nimrod-gileadi** [comment]
Done. Sorry for the missing tag.

**Comment by GaetanLepage** [comment]
Thank you !
