### ISSUE TITLE
Change render viewport resolution

### ISSUE THREAD

**Issue by gabrielpeixoto-cvai** [google-deepmind/dm_control#498]
The render viewport resolution is 640x480 by default. For example, is there an easy way to change this value to 1024x1024?
I searched for the issues and documentation but could not find any straightforward solution.
I am new to Mujoco and dm_control. I have seen discussions that involve manually creating a glfw window and assigning it to mujoco, but I did not find an equivalent process in dm_control.
I appreciate if someone can provide some link or some example code.

**Comment by yuvaltassa** [comment]
https://mujoco.readthedocs.io/en/latest/XMLreference.html#visual-global-offwidth
